### ISSUE TITLE
[panic] Normalizing vechain transaction

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#312]
from logs:

```
2019-09-06T01:41:14.118835+00:00 app[observer.1]: panic: runtime error: invalid memory address or nil pointer dereference
2019-09-06T01:41:14.118844+00:00 app[observer.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xadaf1a]
2019-09-06T01:41:14.118847+00:00 app[observer.1]: 
2019-09-06T01:41:14.118849+00:00 app[observer.1]: goroutine 5243 [running]:
2019-09-06T01:41:14.118882+00:00 app[observer.1]: github.com/trustwallet/blockatlas/platform/vechain.NormalizeTransaction(0x0, 0xc0006ff7b0, 0x1, 0x1378fa8)
2019-09-06T01:41:14.118893+00:00 app[observer.1]: 	/tmp/build_1c03a870fba4087ca93a203a6f0739b1/platform/vechain/api.go:270 +0x3a
2019-09-06T01:41:14.118967+00:00 app[observer.1]: github.com/trustwallet/blockatlas/platform/vechain.(*Platform).GetBlockByNumber(0x1358dc0, 0x38ed72, 0x7f77756c4b28, 0x0, 0x28)
2019-09-06T01:41:14.118974+00:00 app[observer.1]: 	/tmp/build_1c03a870fba4087ca93a203a6f0739b1/platform/vechain/api.go:53 +0x18d
2019-09-06T01:41:14.119057+00:00 app[observer.1]: github.com/trustwallet/blockatlas/observer.retry(0x5, 0x12a05f200, 0xc0006ffaa0, 0x38ed72, 0xc0002cd3b0, 0xc00023c5d0, 0x0, 0xc000496008)
2019-09-06T01:41:14.119065+00:00 app[observer.1]: 	/tmp/build_1c03a870fba4087ca93a203a6f0739b1/observer/retry.go:17 +0x4b
2019-09-06T01:41:14.119104+00:00 app[observer.1]: github.com/trustwallet/blockatlas/observer.(*Stream).loadBlock(0xc0001ad020, 0xc0002c29c0, 0x38ed72)
2019-09-06T01:41:14.119134+00:00 app[observer.1]: 	/tmp/build_1c03a870fba4087ca93a203a6f0739b1/observer/stream.go:90 +0x14d
2019-09-06T01:41:14.119139+00:00 app[observer.1]: created by github.com/trustwallet/blockatlas/observer.(*Stream).load
2019-09-06T01:41:14.119172+00:00 app[observer.1]: 	/tmp/build_1c03a870fba4087ca93a203a6f0739b1/observer/stream.go:80 +0x316
2019-09-06T01:41:14.204658+00:00 heroku[observer.1]: State changed from up to crashed
2019-09-06T01:41:14.172778+00:00 heroku[observer.1]: Process exited with status 2
```

**Comment by madcake** [comment]
Fix https://github.com/trustwallet/blockatlas/pull/315
