### ISSUE TITLE
[Panic] Interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#314]
From logs

```
2019-09-06T02:35:22.403418+00:00 app[observer.1]: time="2019-09-06T02:35:22Z" level=info msg="Got new block" num=10812242 platform=poa txs=0
2019-09-06T02:35:22.443382+00:00 app[observer.1]: time="2019-09-06T02:35:22Z" level=info msg="Got new block" num=598090 platform=zcash txs=5
2019-09-06T02:35:22.489916+00:00 app[observer.1]: panic: interface conversion: interface {} is nil, not string
2019-09-06T02:35:22.489919+00:00 app[observer.1]: 
2019-09-06T02:35:22.489925+00:00 app[observer.1]: goroutine 55 [running]:
2019-09-06T02:35:22.489976+00:00 app[observer.1]: github.com/trustwallet/blockatlas/observer/storage/redis.(*Storage).GetAddressFromXpub(0xc0001908a0, 0x85, 0xc00002c080, 0x6f, 0xc00002c080, 0x6f, 0x0, 0x0, 0x0)
2019-09-06T02:35:22.489989+00:00 app[observer.1]: 	/tmp/build_af8aa7701e7d58fc79c975db541de344/observer/storage/redis/storage.go:70 +0x3a7
2019-09-06T02:35:22.490011+00:00 app[observer.1]: github.com/trustwallet/blockatlas/observer.(*Observer).processBlock(0xc000257be0, 0xc00024bec0, 0xc00035a6f0)
2019-09-06T02:35:22.490027+00:00 app[observer.1]: 	/tmp/build_af8aa7701e7d58fc79c975db541de344/observer/observer.go:55 +0x531
2019-09-06T02:35:22.490041+00:00 app[observer.1]: github.com/trustwallet/blockatlas/observer.(*Observer).run(0xc000257be0, 0xc00024bec0, 0xc00024be60)
2019-09-06T02:35:22.490055+00:00 app[observer.1]: 	/tmp/build_af8aa7701e7d58fc79c975db541de344/observer/observer.go:28 +0x53
2019-09-06T02:35:22.490061+00:00 app[observer.1]: created by github.com/trustwallet/blockatlas/observer.(*Observer).Execute
2019-09-06T02:35:22.490075+00:00 app[observer.1]: 	/tmp/build_af8aa7701e7d58fc79c975db541de344/observer/observer.go:22 +0x71
2019-09-06T02:35:22.551247+00:00 heroku[observer.1]: Process exited with status 2
```

**Comment by Pantani** [comment]
#316
